services:
  db-dev:
    container_name: db-validapix-dev
    image: "postgres:14.15-alpine3.21"
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - "db-dev:/var/lib/postgresql/data"
    environment:
      - POSTGRES_USER=valida_pix
      - POSTGRES_PASSWORD=valida_pix-dev
      - POSTGRES_DB=validapix

volumes:
  db-dev: